version: '3.8'

services:
  # Service API Node.js
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - AI_SERVICE_URL=http://distilbart:8080
      - PORT=5000
    depends_on:
      - distilbart
    volumes:
      - ./uploads:/app/uploads
    networks:
      - ai-network
    restart: unless-stopped

  # Service IA DistilBART
  distilbart:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MODEL_NAME=sshleifer/distilbart-cnn-12-6
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - model-cache:/app/cache
    networks:
      - ai-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

networks:
  ai-network:
    driver: bridge

volumes:
  model-cache: