FROM node:18-alpine

WORKDIR /app

# Créer le dossier uploads
RUN mkdir -p /app/uploads

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm ci --only=production

# Copier le reste de l'application
COPY . .

# Exposer le port
EXPOSE 5000

# Démarrer l'application
CMD ["node", "server.js"]